### ISSUE TITLE
Where to find the Application Insights button in demo module 5

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#110]
I cannot find the Application Insights icon in the 20532C_DEMO_05-monitoring_a_web_application.md demo. Application insights in now in Preview and located in the More Services blade.

Perhaps update the demo steps starting from step 29.

**Comment by seesharprun** [comment]
Here's the relevant instructions:

---

1. On the Start screen, locate and click the **Visual Studio 2015** tile.

  > **Note:** You might have to use the down arrow to locate the Visual Studio 2015 tile on your Start screen.

1.  On the **File** menu, point to **New**, and then click **Project**.

1.  In the **New Project** dialog box that displays, perform the following steps:

	a.  Expand **Templates**, expand **Visual C\#**, and then click **Web**.

	b.  Click **ASP.NET Web Application**.

	c.  In the **Name** box, type **Contoso.Help**.

	d.  In the **Location** box, type **F:\\Mod05\\Democode**.

	e.  Ensure that the **Add Application Insights to Project** check box is selected.

    > If you are not already signed in to your Azure account, you will be prompted to sign in at this point.

	a.  In the **Send telemetry to** list, select **New Application Insights resource**.

	b.  Click **OK**.

---

And here's a screenshot:

![Visual Studio Application Insights](http://s12.postimg.org/q47r3xltp/2016_09_21_23_20_57.jpg)

How could I improve these steps so that your students will understand them right away.

**Comment by molenaar** [comment]
Its not about that part. That part is clear. 
Its about: 
30. In the website blade, locate the Summary section and the tile that displays the Application Insights icon in your resource group.

The Summary tile contains a reference to your resource group, a large icon for your Website, and small icons for related resources, such as a SQL Database instance, your hosting plan, and an Application Insights instance. A purple-colored light bulb icon represents the Application Insights hyperlink.

I cannot find that title on the summary page of the website (=app service). Step 31, 32, and so on is the way I go to the Application Insights.

**Comment by seesharprun** [comment]
I see now. Let me propose a PR with screenshots and then I will reference it here so you can review it.
