### ISSUE TITLE
Solutions files

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#146]
Some students are not that advanced as a developers. Is is possible to add a solution folder with the desired results (without storage account information of course)?
Or otherwise a piece of code at the end of this exercise: "the result should look like this".

The current solutions are working very smooth. Keep up the good work!

**Comment by seesharprun** [comment]
Great idea. When the A release was created, we couldn't figure out an ideal way of creating a solution folder because of storage credentials. Students expect a solution folder to "just work" without any lab steps.

I played with the idea of an Azure RM template in the solution folder that deploys the solution and adds storage connection strings. Would that work for your students?

**Comment by molenaar** [comment]
Just the updated .cs files (fully implemented) would be sufficient. Student can verify the solution files for typos. Some implement it before the wrong closing bracket or in a different method or file.

Lab
->Starter
->->Contoso.Events
(full directory)
->Solution
->a list of changed files
or 
Lab
->Starter
->->Contoso.Events
(full directory)
->Solution
->a list of changed files
->subfolder
->->only the changed files in that folder

![image](https://cloud.githubusercontent.com/assets/10166617/19190332/4083534a-8c9d-11e6-9f57-2f8c973c064e.png)

**Comment by seesharprun** [comment]
Agreed, I will start work on this and update this issue when done.

**Comment by andrewbeldean** [comment]
Hi....

Did this ever get completed as it would be very useful?

**Comment by seesharprun** [comment]
This was punted to the next update. We will definitely add solution files and we will make sure they have "blank" values for each setting.
