### ISSUE TITLE
Identify workloads that can and cannot be deployed

### ISSUE THREAD

**Issue by anand80** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#154]
Hi There, Where Can I Get The List For Workloads That Can & Cannot Be Deployed on ARM Virtual Machines ? Exam 70-532 Been scrambling around...and yet to obtain any leads.

**Comment by seesharprun** [comment]
My understanding is that the same workloads are supported in both ASM and ARM virtual machines. Within the VM guest OS, there's fundamentally no difference. The differences are largely in how the VMs are hosted and configured in Azure.

For a list of supported server software, I would look here: https://support.microsoft.com/en-us/kb/2721672. This is only software where you can open a support request. You can install whatever you want even if it's not on the list but you won't be able to open a support request for that software.

Does this help? If not, can you give an example of what you are looking for?

**Comment by rajbalakrish** [comment]
@seesharprun The question from Anand is infact an Exam Objective in 70-532 but it's quite unclear to determine a defined list of Workloads that can and cannot be deployed in Azure. In Principle the Workloads that appear in azure marketplace are those that can be deployed and those that do not exist are those that cannot be deployed. Is that correct ? @anand80 - This is bit abstract but i do not have a better answer at this moment

**Comment by AIF2015** [comment]
I had the exact same question @anand80.  I wanted something more tangible as an answer.  But @rajbalakrish stated "In Principle the Workloads that appear in azure marketplace are those that can be deployed and those that do not exist are those that cannot be deployed."  Not the answer I was hoping for but I get it.  Whatever is in the selection of the Marketplace is what defines deployable and if it's not... it cannot be deployed. Well that's the way I understand it.

**Comment by rajbalakrish** [comment]
@AIF2015 I think this is what you are looking for http://mstechazure.blogspot.nl/2017/03/identify-workloads-that-can-and-cannot.html

**Comment by AIF2015** [comment]
That is exactly what I was looking for.  Thank you so much for finding that!  I was thinking there has to be a list that's compiled already or somewhere on Microsoft support site.  Again, thank you for that information. Definitely answered my question. @rajbalakrish

**Comment by seesharprun** [comment]
That great article is based on this link: https://support.microsoft.com/en-us/help/2721672/microsoft-server-software-support-for-microsoft-azure-virtual-machines

I can see why Microsoft is hesitant to release a strict yes/no list. On an almost monthly basis, the list would be outdated.

**Comment by AIF2015** [comment]
Yes, @seesharprun we can definitely expect the list to continue to change. But it does give us a starting place to reference what's currently offered and what isn't. I guess that's one of those things we have to periodically check to stay up to date.

**Comment by seesharprun** [comment]
100% agree

**Comment by rajbalakrish** [comment]
Honestly I am not fully convinced on that list either !! Simply because they are a set of unsupported features NOT workloads that cannot be deployed :(  Windows Server 2003 R2 is a workload that's no longer supported on Azure but that doesn't mean this workload cannot be deployed !! You can prepare a specialised VHD and get this done !! So this exam objective is a bit unclear to me .. i took 70-532 but never came across a question on this topic !!

**Comment by ConcreteGannet** [comment]
Hi all,

I think there are two categories here: things that won't be available within a virtual machine because there's an Azure way of doing it, and things that aren't available because Microsoft haven't bothered yet.

The first category is the important one. As others have said, the second category might change at any time. There is a good exam question trying to emerge here. Any question should only test you on important things from the first category. A competent developer using Azure should know Network Load Balancing is not available, and if they need it to use Azure load balancing.

Cheers

Paul Foxworthy
