### ISSUE TITLE
Use Azure CLI 2.0

### ISSUE THREAD

**Issue by Misiu** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#195]
In module 9 old CLI is used. New one was released (https://docs.microsoft.com/en-us/cli/azure/overview?view=azure-cli-latest)

This is quote from [MS site](https://docs.microsoft.com/en-us/azure/cli-install-nodejs):

> This topic describes how to install the Azure CLI 1.0. This CLI is **deprecated** and should only be used for support with the Azure Service Management (ASM) model with "classic" resources. For Azure Resource Manager (ARM) deployments, use Azure CLI 2.0.

**Comment by tiagocostapt** [comment]
You can read at https://github.com/MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions/issues/179 that the team is working in a new course versions that should release soon.

**Comment by Misiu** [comment]
@tiagocostapt thank for update.
Do You have any information when it might get released?
I'm in the middle of course right now (for which I had to pay of course) and it's bit disappointing that I can't finish Labs because of those materials.
I have some $$ left on my Azure so as soon as new version will be released I'd like to go thru all of labs ones again.

**Comment by tiagocostapt** [comment]
I teach the course and I'm currently teaching that course and my next module is Mod10 I always demo to my students how to create new Azure AD Directories in the new Portal. The lab is possible to take in the current Portal, your trainer just need to adapt it. You can read more information at: https://docs.microsoft.com/en-us/azure/active-directory/get-started-azure-ad on how the Azure AD service works and how to create the new directory that is asked on the lab. In resume you just need to go to the "+ Create a resource" option in the portal and type "Azure Active Directory" then you can create you new Azure AD.

**Comment by seesharprun** [comment]
We are working on an update of the entire course right now to fix this and the update is due before the end of March.

**This update will include a push of the Azure CLI labs to CLI 2.0.**

The biggest challenge with this update is restructuring the repository so that it works identically to the [MicrosoftLearning/20535-ArchitectingMicrosoftAzureSolutions repository](https://github.com/MicrosoftLearning/20535-ArchitectingMicrosoftAzureSolutions). That involves adding a Docker image, creating a Node.js build script and finally reshuffling the content.

**Comment by seesharprun** [comment]
I created a new release (**1.2.1**) based on @Pablites commits and have released it here: https://github.com/MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions/releases/tag/C-v.1.2.1

This is going to be the last release for 20532C until we release 20532D towards the end of March.

**Comment by Misiu** [comment]
@seesharprun awesome news!
looking forward for new release. I definitively must do all labs again.
BTW do You plan to migrate to .NET Core?

Also it would be grate to include steps to move Contoso.Events.Worker into Azure (now it is standalone app, ideally it should be Web Worker, or something similar - Event Grid and Functions, I'm all new to this, so don't know yet what would be best solution). My idea is to have whole solution published to Azure without anything on-premise.

Also SignalR could be included. Now when You go to course in Admin App You must refresh site after a while to see links. Ideally Web Worker should do its work and it should notify Admin App using SignalR.
That would be awesome addition :)

**Comment by seesharprun** [comment]
Officially, we don't have plans to .NET Core as part of the D release

Unofficially, when I did epic/sprint planning, we sorted goals by priority and this was the highest-priority stretch goal. There's a very good chance that the next set of labs will use .NET Core.

As for your other suggestions:
- Contoso.Events.Worker will be an Azure Function in the D release. The function will be triggered by a Queue message (Storage or Service Bus)
- I hate the storage emulators. Those are going away in the D release.
- We thought about including SignalR but it didn't make the cut for the D release. The primary reason was that we already have a SignalR lab in the ASP.NET course. The other issue we ran into was that many students would have trouble adding the correct settings into the Function App so that it could call the SignalR hub. The Function App will need a URL, preferably stored in App Settings, pointing it to the Web App where the hub is hosted. I still want to see this happen.

**Comment by seesharprun** [comment]
As a quick follow-up. Running .NET Core on Azure Functions (for SignalR support) is not quite ready yet. The .NET Core version of SignalR is still in alpha and the .NET Core runtime for Azure Functions is still in beta.

We can come back and re-open the discussion around adding SignalR to the lab application once both of those services are formally released and there's more documentation around them.
