### ISSUE TITLE
Clarification Please

### ISSUE THREAD

**Issue by pdlab** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#219]
When downloading the current 4.1.30 Allfiles and lab instructions.......
- I  don't see all the modules only 3-11  (1-2 missing)
- I don't see lab instructions for 3-11    (1-2 only present)

Is this accurate and is this all that's need for the teach?

Thanks.

**Comment by seesharprun** [comment]
Modules 1 & 2 do not have labfiles so you will not see folders for those two modules in the Allfiles.

When the repository was reverted, all of the high-level lab instructions for Modules 1-11 were missing. I recently fixed the issue for Modules 1 & 2 but have not fixed it yet for Modules 3-11. Due to the holidays, progress was slow. I expect to have the high-level instructions for Modules 3-11 fixed by next week.

I have been advising MCTs to have the students use the Lab Answer Keys as their primary lab instructions in the interim until I can finish this fix. The Lab Answer Keys are available for all labs.

**Comment by pdlab** [comment]
That all makes sense now.   :)   
Thank you!

**Comment by seesharprun** [comment]
I will leave this issue open until the high-level instructions for Modules 3-11 are fixed.

**Comment by seesharprun** [comment]
The instructions are fixed in version [4.2.45](https://github.com/MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions/releases/tag/D-v4.2.45)
