### ISSUE TITLE
Dev VM with Visual Studio 2017 is outdated

### ISSUE THREAD

**Issue by HofmT** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#221]
# Module: 03
#### Step: 05

**Description of issue**
Visual Studio 2017 won't build the solution.

**Repro steps**:
Follow the instructions from module 02 to set up a VM with Visual Studio 2017.

**Solution**:
Visual Studio needs to be, after setting up the machine, manually updated.

My suggestion is to add this information to the instruction of module 02 where the VM is originally set up.

**Comment by HofmT** [comment]
In my case, I simply updated Visual Studio inside the VM. 
- After logging in to the VM, open Visual Studio 2017
- Inside VS 2017, go to _Tools_ then _Extensions and Updates_ and install latest update

**Comment by seesharprun** [comment]
There's also the "Visual Studio Installer" tool that you can open from the Start Menu.

I am going to try both ways to see which one ends up in clearer instructions.

**Comment by jasonrmh** [comment]
Visual Studio on the VM is initially at a version (15.6) that requires update in order to use .Net Core 2.0, which is required to build lab projects.
Updating to the latest version of Visual Studio (15.7.3 or above) resolves the issue, but it is a large update and takes some time to complete.
I could not find Visual Studio Installer initially, so used Tools > Extensions and Updates.
After update to 15.7, Visual Studio Installer is available.

**Comment by jasonrmh** [comment]
Agreed, but @HofmT was saying to add the steps to upgrade as part of the lab instructions, or at least a note to check to VS VERSION and .net core version, as having an old version will lead to build errors and takes more time to investigate / resolve.

**Comment by seesharprun** [comment]
I understand now. I thought he problem was that the upgrade took too long.

**Comment by paul-mercer** [comment]
When running it I just instructed the delegates to complete the lab and once everything else was done to the check for and install any updates to Visual Studio. Once it started the update process we just moved onto the delivery of the next module and it was finished well before it was required for module 3's lab.

I think that adding a final stage to the lab to check for and then install any updates would work fine, if the image is update with a newer version of VS then there will be nothing to do anyway.

**Comment by seesharprun** [comment]
I’ll try using your method.

When I tested some instructions that had the student update VS immediately, it failed test due to taking too long.

I’m just as frustrated as everyone else that the official Visual Studio image in Azure is no longer up-to-date.

**Comment by seesharprun** [comment]
This issue is still open and I don't have any update. I still don't know why the official Visual Studio image in Azure is lagging behind this significantly. The Error Log for the course should say to have the student manually update Visual Studio 2017.

Since that's not the ideal scenario, I debated updating the instructions and tentatively chose not to update them. As with everything else, this is up for debate.
