### ISSUE TITLE
Lab ex-1 10

### ISSUE THREAD

**Issue by Usamawahabkhan** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#224]
# Module: 10
#### Step: 6

Description of issue
after deploying from vs to webapp giving and error on published portal. 502.5 Process failure error.

any idea? 
in logs requesting to vm name don't know why?
Repro steps:

1.
1.
1.

**Comment by NFGodoy** [comment]
I had a server error in this lab that was fixed after I reset the password for SQL Server in the Azure portal. 

--------------------------------------------
On Thu, 28/6/18, Usamawahabkhan <notifications@github.com> wrote:

 Subject: [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions] Lab ex-1 10 (#224)
 To: "MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions" <20532-DevelopingMicrosoftAzureSolutions@noreply.github.com>
 Cc: "Subscribed" <subscribed@noreply.github.com>
 Received: Thursday, 28 June, 2018, 11:49 PM
 
 Module: 10
 Lab/Demo: 10
 Task: 3
 Step: 6
 Description of issue
 
 after deploying from vs to webapp giving and error on
 published portal. 502.5 Process failure error.
 any idea?
 
 in logs requesting to vm name don't know why?
 
 Repro steps:
 
 
 
 
 
 
 —
 You are receiving this because you are subscribed to this
 thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by seesharprun** [comment]
I wonder if the passwords have a mismatch in the instructions.

________________________________

**Comment by seesharprun** [comment]
I have checked and I can't find a mismatched password. If you run into this problem again, please re-open this issue.
