### ISSUE TITLE
Lab 2 - Task 2: Create a Virtual Machine 

### ISSUE THREAD

**Issue by tschrist** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#231]
# Module: 01
#### Step: 9a (they're all a?)

Description of issue: During Create VM where Network Security Group left as "Basic" requires you to Select a Public Inbound Port: _These ports will be exposed to the internet. Use the Advanced controls to limit inbound traffic to known IP addresses. You can also update inbound traffic rules later._

Repro steps:

9. In the Create Virtual Machine blade, click Settings and perform the following steps:
a. Under the Storage > Use managed disks section, select the No option.
a. Click the Storage Account section and then select stor20532[your name here].
a. Click the Virtual Network section and then select vnet20532.
a. Click the Subnet section and then select Apps.
a. Leave default values for **Public IP Address, Network Security Group (firewall), Extensions** and **High availability**.

if you leave Network Security Group (firewall) to default, you're required to add a port for access.  You can either: a) leave default and pick RDP (3389) for acces, or b) select advanced, create new, 1000: default-allow-rdp, Any, RDP (TCP/3389)

also, can the numbering/lettering be updated to not be all a.'s ?
![rdp-required](https://user-images.githubusercontent.com/2255750/43555402-cab2838a-95ae-11e8-8b16-3152590dc299.PNG)

**Comment by seesharprun** [comment]
Being required to choose a public inbound port was a very recent change in the portal so I will need to update the steps.

**We should probably have a different issue to talk about the lettering.** They appear as all a's in markdown as that's the way to get the Word document to output lists using letters instead of numbers. 

![image](https://user-images.githubusercontent.com/5067401/43594759-076c9adc-9649-11e8-8fa4-558fd6be059d.png)

Technically, lists using letters instead of numbers are not part of the Markdown spec and will not render properly in HTML. This was a "less of two evils" decision to go with all a's.

**Comment by ConcreteGannet** [comment]
Markdown is a mess. Please consider AsciiDoc, which will handle this issue perfectly well: http://www.methods.co.nz/asciidoc/chunked/ch17.html .

**Comment by tiagocostapt** [comment]
@tschrist this should be fixed on a recent PR.
