### ISSUE TITLE
Labs 7 and 8 are broken after September 1, 2018 Update

### ISSUE THREAD

**Issue by wwherman** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#234]
# Module: 07
#### Step: 04

Description of issue
Build fails due to NuGet package compatibility issue.

Repro steps:
Labs 6, 7, and 8 have this error but Labs 7 and 8 fail without this fix.
1.	In Solution Explorer, right-click Contoso.Events and select Manage NuGet Packages for Solution.
2.	Click the Updates tab.
3.	Select the check box for Select all packages.
4.	Click Update.
5.	In the Preview Changes dialog box, click OK.
6.	In the License Acceptance dialog box, click I Accept.
7.	Wait for the updates to complete.
8.	In the Manage Packages for Solution window, click the Browse tab.
9.	Search for Microsoft.Azure.WebJobs.Extensions.Storage. 
10.	Select the check box to Include prerelease packages.
11.	In the packages pane, select Microsoft.Azure.WebJobs.Extensions.Storage.
12.	On the right side of the window, select the check box for Contoso.Events.Worker.
13.	In the Version drop-down list, select 3.0.0-rc1.
14.	Click Install. 
15.	In the Preview Changes dialog box, click OK.
16.	In the License Acceptance dialog box, click I Accept.
17.	Wait for the updates to complete.

**Comment by wwherman** [comment]
Correction - Module 8 is still broken. Some of the NuGet packages in the solution are releasing new versions on a daily basis but no fix yet for the last section of Exercise 2.

**Comment by ptreptau** [comment]
I can confirm that Lab 6,7,8 are broken. Additionally, numerous demo instructions after Mod3 are missing from the release and quite a few slides do not match with the PowerPoint Content (i.e. IoT additions in Mod 8 are completely missing from the PPT and Trainer Handbook).

New storage accounts provisioning in Portal has to be added (currently features the "old" way in the Azure Portal).

Also, students have noted that the labs 6,7,8 are repetitive and time-consuming (reprovision SQL, storage and Cosmos DB in every lab and editing config files) to re-provision for every lab, esp. MOD6-8.

**Comment by seesharprun** [comment]
This has been a disaster trying to nail down and resolve. Let me address each of your items one-by-one:

1. I'm working on fixing labs 6-8. The new Azure Functions launch has been rocky and I am trying to figure out how to "freeze" the WebJobs dependency so the course doesn't break again when they eventually release Azure Functions 3.0. If you have any ideas on how to fix this, please issue a PR as this has been a tough bug to fix.
1. There are numerous misprints that causes discrepencies in the PPTX, Trainer Handbook and student manual. Unfortunately, I can't really do much about that here on the GitHub repos. Please complain about that loudly on the MCT support channels so that someone at Learning can help solve that problem.
1. One of the side effects of the misprints is that the trainer guide calls for Demos in Modules 3-11. One of the design decision when I updated 20532C to 20532D was to drop any demos after Module 2 and move to more visual slides and longer hands-on labs. The demos were exponentially more difficult to maintain as the portal changed. Somehow, many slides were misprinted in the student manuals and the old demo slides were shipped with the course. We can debate here whether that was the right design choice or not.
1. Both the Storage Account and Cloud Shell provisioning experiences have changed. I will need to update both.
1. One of the design rules of MOC labs is that they labs really shouldn't depend on each other. Many learning partners will take a few modules from each course and deliver them independently. If we create a Cosmos instance in Lab 5 and then look for it in Lab 6, it may not be there. I hate the repetitiveness but it seems there's no way around it if the course is sold as modules. In 20535, we solved this by using ARM templates at the start of almost every lab. I get the opposite complaints there where a lot of people say the labs are too short since everything is "auto provisioned". I would use ARM templates in 20532, but it's not required learning in the pre-reqs and it's not really part of the exam OD. I can't make a lot of assumptions that the student really knows how to deploy an ARM template. In 20535, I can assume that the student knows about ARM templates based on the pre-reqs for that course.

Everything I said is my opinion and not a rule. If you disagree, let's talk about it.

I have a tester resource available next week so I think I can get this done by 9/28. Let's keep this thread open while we work through issues.

**Comment by ElaMark** [comment]
Hi Sidney, I really appreciate your explanation and commentary on issues such as this. It gives me the opportunity to pass this information on to the students where they have a better appreciation of the complexities involved with a course that is based on a rapidly changing technology, and that must comply with the requirements of MS learning. In that way they're not so upset if a lab doesn't work for a while. Cheers, Mark

**Comment by seesharprun** [comment]
Quick update everyone...

I have been out-of-office with a medical emergency since the last message. I will most likely be out for another week or so.

I am working now on securing another resource to go in and fix these issues either later this week or early next week.
