### ISSUE TITLE
Module 8 LocalDb Error, No Sign-in Sheets, No Files for Exercise 4

### ISSUE THREAD

**Issue by ramsamdam** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#76]
1. When I open module 8 ContosoEvents.sln I am getting a prompt to install LocalDb nothing is mentioned about that in the manual instructions

2. After performing all steps in Exercise 1,2 and 3 I am unable to generate Sign-in Sheets, and I have explicitly added references which I was getting 

3. There are no Relay Files present in the lab files of Module 8

**Comment by seesharprun** [comment]
1. The LocalDb prompt has now been fixed. The VMs do have LocalDb installed but Visual Studio should not have prompted you about this.

2. I believe I have fixed the bugs.

3. The relay portion of this lab has been removed since this evolved from a 5-day to a 4-day course. I am open to adding it back as an "optional" lab if someone is willing to work on a PR with me on it. I just don't have the time to tackle that alone.

This issues should be resolved in the latest PR #82. This should close the issue.

**Comment by ramsamdam** [comment]
Just Finished the Execution of Module 8,

LocalDb Error is now Fixed , I was getting the same error in Module 10 is that also fixed?

I am able to generate sign in sheets in Exercise 2 , but I am still not able to generate the Sign In Sheets in Exercise 3 facing no error, have done refreshing and waited for 30 minutes.
