### ISSUE TITLE
Module 3 demo instructions don't match the Visual Studio solution

### ISSUE THREAD

**Issue by ElaMark** [MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions#89]
The instructions at https://github.com/MicrosoftLearning/20532-DevelopingMicrosoftAzureSolutions/blob/c-release/Instructions/Demos/dotnet/Mod03/20532C_DEMO_03-contoso_events_walkthrough.md,

- Still describe the demo steps when the  application when it used a Cloud service.
- Forget to mention that the Lodging WCF service must be started.
- Don't mention that one needs to create a service bus namespace and change both the C# code in the Lodging WCF service and the Config of the web Application
- Still refer to Visual Studio 2013.

**Comment by seesharprun** [comment]
I created a branch for this and will have it resolved before the end of the week.

Behind the scenes, I merged in a bunch of Markdown files for the demos and somehow "screwed up" the PR and merges and got the old versions of the demos. I'm working on a fix for this now and you can track it in this PR.

Thanks for the heads up and all of your proactive issue resolutions and finds!

**Comment by ElaMark** [comment]
I'm running the course this week and I'll keep you up-to-date with anything we find.

You've been doing a great job on this over the past year, thanks for being so responsive. This approach to courseware has been very good.

Cheers, Mark

**Comment by seesharprun** [comment]
Thanks. I'm just starting to manage this course on GitHub and i'm trying to use Pull Requests and other methods to be very transparent about it.  Last year it was managed by a cool training company <http://opsgility.com> and they tried to keep the B version up to date too. Since i'm new, feel free to use the issues here on GitHub to make recommendations or have conversations about how you and other MCT would like to see this course transform over the long term.

Hopefully you are able to run the 20532C release and can take advantage of the latest and greatest labs. The demo update has lagged a bit but it's still coming soon.

**Comment by nicolasploquin** [comment]
Thanks for comments,
@ElaMark, did you find any others errors in lab statements ? (labs 8/9/10)
Nicolas

**Comment by ElaMark** [comment]
None that my students reported. (Other than there are no instructions for setting up the service relay bus in lab 8)

**Comment by seesharprun** [comment]
I believe that this is resolved now. Please reopen if it is not resolved.

**Comment by molenaar** [comment]
Walkthrough talks About selecting the Cloud and Management Projects as Startup project. However the demo Solution doesn't have these Projects.

**Comment by molenaar** [comment]
The demo instructor a fine, however I think we still see the old democode in the allfiles.
